Add more tests

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -60,24 +60,40 @@ jobs:
         with:
           args: get deployments
           output_variable: DEPLOYMENTS
-      - name: Check Output
+      - name: Check for expected output
         run: |
-          error=0
-          if [ -z "$DEPLOYMENTS" ]; then
-            echo "ERROR: DEPLOYMENTS is empty"
-            error=1
-          else
-            echo "DEPLOYMENTS: $DEPLOYMENTS"
-          fi
-          if [ -z "$POD_NAMES" ]; then
-            echo "ERROR: POD_NAMES is empty"
-            error=1
-          else
-            echo "POD_NAMES: $POD_NAMES"
-          fi
-          if [ "$error" -eq 1 ]; then
-            exit 1
-          fi
+            error=0
+            echo "Starting Check Output step"
+            echo "Checking DEPLOYMENTS variable"
+            if [ -z "$DEPLOYMENTS" ]; then
+              echo "ERROR: DEPLOYMENTS is empty"
+              error=1
+            else
+              echo "DEPLOYMENTS: START_VALUE"
+              echo "$DEPLOYMENTS"
+              echo "DEPLOYMENTS: END_VALUE"
+              # Check if DEPLOYMENTS has more than one line
+              if [[ $(echo "$DEPLOYMENTS" | wc -l) -le 1 ]]; then
+                echo "ERROR: Expected a multiline string for DEPLOYMENTS but found single line or less"
+                error=1
+              fi
+            fi
+            echo "Finished check for DEPLOYMENTS"
+            echo "Checking POD_NAMES variable"
+            if [ -z "$POD_NAMES" ]; then
+              echo "ERROR: POD_NAMES is empty"
+              error=1
+            else
+              echo "POD_NAMES: START_VALUE"
+              echo "$POD_NAMES"
+              echo "POD_NAMES: END_VALUE"
+            fi
+            echo "Finished check for POD_NAMES"
+            if [ "$error" -eq 1 ]; then
+              echo "Exiting with error code 1"
+              exit 1
+            fi
+            echo "Finished Check Output step"
       - name: Delete Resources
         uses: ./
         with:
